# Generated by Django 2.0.3 on 2018-03-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discusion',
            new_name='Discussion',
        ),
    ]
