# Generated by Django 2.0.3 on 2018-03-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0002_auto_20180327_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='name',
        ),
        migrations.RemoveField(
            model_name='point',
            name='given_points',
        ),
        migrations.AddField(
            model_name='decision',
            name='name1',
            field=models.CharField(default='hjh', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decision',
            name='name2',
            field=models.CharField(default='gf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='given_points_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='point',
            name='given_points_2',
            field=models.IntegerField(default=0),
        ),
    ]
