# Generated by Django 2.0.3 on 2018-04-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0003_auto_20180328_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='is_published',
            field=models.IntegerField(default=0),
        ),
    ]
